In [1]:
#Imports
import pandas as pd
import numpy as np
from numpy import delete
import scipy.stats as stats

#Código necesario para correr funciones desde otro archivo .ipynb de la misma carpeta
%run Preparar_datos.ipynb
%run TablaResumenCC.ipynb

# Índice: Qué hay en el documento
 ¿Las oscilaciones diarias vienen del ramal?
- CCs sin suavizar de Tc-Te, Tc-Tr y Tr-Te
- CCs con los datos suavizados de Tc-Te, Tc-Tr y Tr-Te

Significado de las abreviaturas:

- CC: Coeficientes de correlación
- Tc: Temperatura del Cruce (ºC)
- Te: Temperatura del exterior (ºC)
- Tr: Temperatura del ramal del cruce (ºC)

Solo obtener la información para los mese con oscilaciones claras:
- 1) Los meses con oscilaciones claras para el C02 del cruce son: 
 Julio, agosto y septiembre de 2021.
 Junio, julio, agosto y septiembre de 2022
- 2) Los meses con oscilaciones claras para el CO2 del hall son:
Julio, agosto, septiembre y octubre de 2021. Mayo, junio y julio de 2022

# 1.1) ¿Las oscilaciones diarias vienen del ramal? Coeficientes a partir de las temperaturas sin suavizar

### Preparar datos:

In [3]:
# ###Entrada:
# #Leer los datos
# #2021
# dfEntrada_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA ENTRADA A.xlsx")
# dfEntrada_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA ENTRADA A.xlsx")
# dfEntrada_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
# dfEntrada_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA ENTRADA A.xlsx")
# #2022
# dfEntrada_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA ENTRADA A.xlsx")
# dfEntrada_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA ENTRADA A.xlsx")
# dfEntrada_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA ENTRADA A.xlsx")
# #Unir df:
# dfEntrada_21 = pd.concat([dfEntrada_7_21, dfEntrada_8_21, dfEntrada_9_21, dfEntrada_10_21], axis=0)
# dfEntrada_22 = pd.concat([dfEntrada_7_22, dfEntrada_8_22, dfEntrada_9_22], axis=0)

###Cruce:
#Leer los datos
#2021
dfCruce_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA CRUCE D.xlsx")
dfCruce_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA CRUCE D.xlsx")
dfCruce_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
dfCruce_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA CRUCE D.xlsx")
#2022
dfCruce_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA CRUCE C.xlsx")
dfCruce_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA CRUCE D.xlsx")
dfCruce_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA CRUCE D.xlsx")
#Unir df:
dfCruce_21 = pd.concat([dfCruce_7_21, dfCruce_8_21, dfCruce_9_21, dfCruce_10_21], axis=0)
dfCruce_22 = pd.concat([dfCruce_7_22, dfCruce_8_22, dfCruce_9_22], axis=0)

###Exterior:
#Leer los datos
#2021
dfExterior_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA EXTERIOR.xlsx")
dfExterior_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA EXTERIOR.xlsx")
dfExterior_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
dfExterior_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA EXTERIOR.xlsx")
#2022
dfExterior_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA EXTERIOR.xlsx")
dfExterior_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA EXTERIOR.xlsx")
dfExterior_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA EXTERIOR.xlsx")
#Unir df:
dfExterior_21 = pd.concat([dfExterior_7_21, dfExterior_8_21, dfExterior_9_21, dfExterior_10_21], axis=0)
dfExterior_22 = pd.concat([dfExterior_7_22, dfExterior_8_22, dfExterior_9_22], axis=0)

# ###Policromos:
# #Leer los datos
# #2021
# dfPolicromos_7_21 = pd.read_excel("./altamira/2021/7.JULIO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_8_21 = pd.read_excel("./altamira/2021/8.AGOSTO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_9_21 = pd.read_excel("./altamira/2021/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
# dfPolicromos_10_21 = pd.read_excel("./altamira/2021/10. OCTUBRE/ZONA POLICROMOS.xlsx")
# #2022
# dfPolicromos_7_22 = pd.read_excel("./altamira/2022/7.JULIO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_8_22 = pd.read_excel("./altamira/2022/8. AGOSTO/ZONA POLICROMOS C.xlsx")
# dfPolicromos_9_22 = pd.read_excel("./altamira/2022/9. SEPTIEMBRE/ZONA POLICROMOS C.xlsx")
# #Unir df:
# dfPolicromos_21 = pd.concat([dfPolicromos_7_21, dfPolicromos_8_21, dfPolicromos_9_21, dfPolicromos_10_21], axis=0)
# dfPolicromos_22 = pd.concat([dfPolicromos_7_22, dfPolicromos_8_22, dfPolicromos_9_22], axis=0)

#Resetear los índices de los df:
# dfPolicromos_21= dfPolicromos_21.reset_index(drop=True)
# dfPolicromos_22= dfPolicromos_22.reset_index(drop=True)
dfExterior_21= dfExterior_21.reset_index(drop=True)
dfExterior_22= dfExterior_22.reset_index(drop=True)
dfCruce_21= dfCruce_21.reset_index(drop=True)
dfCruce_22= dfCruce_22.reset_index(drop=True)
# dfEntrada_21= dfEntrada_21.reset_index(drop=True)
# dfEntrada_22= dfEntrada_22.reset_index(drop=True)

#Guardar df  en archivos excel:
dfCruce_21.to_excel('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
dfCruce_22.to_excel('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
dfExterior_21.to_excel('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
dfExterior_22.to_excel('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
# dfEntrada_21.to_excel('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
# dfEntrada_22.to_excel('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
# dfPolicromos_21.to_excel('./DatosDeInteresPorSalasYAños/Policromos21.xlsx')
# dfPolicromos_22.to_excel('./DatosDeInteresPorSalasYAños/Policromos22.xlsx')

# # Datos cada 15 mins Policromos de los archivos unidos:
# DatosPolicromos_21 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Exterior21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Hall21.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Policromos21.xlsx','2021')
# DatosPolicromos_22 = adaptar_len_policromos('./DatosDeInteresPorSalasYAños/Cruce22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Exterior22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Hall22.xlsx',
#                                             './DatosDeInteresPorSalasYAños/Policromos22.xlsx', '2022')
#Separar por semanas:
SemanaCruce21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce21.xlsx')
SemanaCruce22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Cruce22.xlsx')
SemanaExterior21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior21.xlsx')
SemanaExterior22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Exterior22.xlsx')
# SemanaHall21 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall21.xlsx')
# SemanaHall22 = SepararPorSemanas('./DatosDeInteresPorSalasYAños/Hall22.xlsx')
# PolicromosSemanas_2021 = separar_policromos_semanas(DatosPolicromos_21)
# PolicromosSemanas_2022 = separar_policromos_semanas(DatosPolicromos_22)

##Arreglar los problemas en los datos por semanas:
#Semana 8 de 2021:
# PolicromosSemanas_2021[8]=PolicromosSemanas_2021[8][:339]
#Semana 8 de 2021:
# PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9][192:]
# PolicromosSemanas_2021[9]=PolicromosSemanas_2021[9].reset_index(drop=True)
#Semana 0 de 2022:
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][2:]
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0].reset_index(drop=True)
# PolicromosSemanas_2022[0]=PolicromosSemanas_2022[0][:286]
SemanaExterior22[0]=SemanaExterior22[0][:286]
#Semana 4 de 2022:
# SemanaHall22[4]=SemanaHall22[4][:669]
SemanaCruce22[4]=SemanaCruce22[4][:669]
# PolicromosSemanas_2022[4]=PolicromosSemanas_2022[4][:669]
#Semana 13 de 2022:
# PolicromosSemanas_2022[13]=PolicromosSemanas_2022[13][:480]

In [4]:
def cc_Tr_Tc_Te(DataframeCruce, DataframeExterior):#Función adaptada para variables sin suavizar
    """
    Atributos:
    1) DataframeCruce: Lista de dataframes por semanas correspondiente a los datos de un mes de Cruce
    2) DataframeExterior: Lista de dataframes por semanas correspondiente a los datos de un mes de Exterior
    
    Devuelve:
    Una lista de listas, r. Cada elemento de r, r[i] con i=0, 1, 2, 3, 4, es una lista con los coeficiente de correlación y p 
    valores correspondientes a una semana.  r[i] = r_TD_Tr, p_TD_Tr, r_TD_Te, p_TD_Te, r_Tr_Te, p_Tr_Te
    
    ¿A qué corresponde cada elemento de r[i]?
    1) r_TD_Tr: Coeficiente de correlación entre la temperatura del Cruce y del Ramal
    2) p_TD_Tr: P-valor correspondiente a r_TD_Tr
    3) r_TD_Te: Coeficiente de correlación entre la temperatura del Cruce y la exterior
    4) p_TD_Te: P-valor correspondiente a r_TD_Te
    5) r_Tr_Te: Coeficiente de correlación entre la temperatura del Ramal y la exterior
    6) p_Tr_Te: P-valor correspondiente a r_Tr_Te
    """
    i=0
    r=[]
    while i<len(DataframeCruce):
       #print(i)
        DataframeCruce[i].reset_index(drop=True, inplace=True)
        DataframeExterior[i].reset_index(drop=True, inplace=True)
        
        # Variables que me van a hacer falta: Tc, Te, Tr
        for index, _ in DataframeExterior[i].iterrows():#Se va fuera de indice
            if  __builtins__.sum([pd.isna(DataframeCruce[i]["Temperatura D (° C)"][index]),
                                  pd.isna(DataframeCruce[i]['Tr_suavizada'][index]),
                                  pd.isna(DataframeExterior[i]["Tr Exterior (C Tr)"][index])]) > 0:
                DataframeCruce[i].drop([index], axis=0, inplace=True)
                DataframeExterior[i].drop([index], axis=0, inplace=True)

        #Mediante scipy por semanas:
        r_TD_Tr, p_TD_Tr = stats.pearsonr(DataframeCruce[i]["Temperatura D (° C)"], DataframeCruce[i]["tr Cruce Ramal ('C)"])
        r_TD_Te, p_TD_Te = stats.pearsonr(DataframeCruce[i]["Temperatura D (° C)"], DataframeExterior[i]["Tr Exterior (C Tr)"])
        r_Tr_Te, p_Tr_Te = stats.pearsonr(DataframeCruce[i]["tr Cruce Ramal ('C)"], DataframeExterior[i]["Tr Exterior (C Tr)"])
        rs = r_TD_Tr, p_TD_Tr, r_TD_Te, p_TD_Te, r_Tr_Te, p_Tr_Te, len(DataframeCruce[i]["tr Cruce Ramal ('C)"])
        r.append(rs)
        i=i+1
    return(r)

In [5]:
cc21 = cc_Tr_Tc_Te(SemanaCruce21, SemanaExterior21)
cc22 = cc_Tr_Tc_Te(SemanaCruce22, SemanaExterior22)

In [6]:
s1=pd.Series([cc21[0][0], cc21[1][0],cc21[2][0],cc21[3][0],cc21[4][0],cc21[5][0],cc21[6][0],cc21[7][0],cc21[8][0],cc21[9][0],
              cc21[10][0], cc21[11][0], cc21[12][0], cc21[13][0], cc21[14][0], cc21[15][0], cc21[16][0], cc21[17][0], 
              cc22[0][0], cc22[1][0],cc22[2][0],cc22[3][0],cc22[4][0],cc22[5][0],cc22[6][0],cc22[7][0],cc21[8][0],
              cc22[9][0], cc22[10][0], cc22[11][0], cc22[12][0], cc22[13][0]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s2=pd.Series([cc21[0][1], cc21[1][1],cc21[2][1],cc21[3][1],cc21[4][1],cc21[5][1],cc21[6][1],cc21[7][1],cc21[8][1],cc21[9][1],
              cc21[10][1], cc21[11][1], cc21[12][1], cc21[13][1], cc21[14][1], cc21[15][1], cc21[16][1], cc21[17][1], 
              cc22[0][1], cc22[1][1],cc22[2][1],cc22[3][1],cc22[4][1],cc22[5][1],cc22[6][1],cc22[7][1],cc21[8][1],
              cc22[9][1], cc22[10][1], cc22[11][1], cc22[12][1], cc22[13][1]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s3=pd.Series([cc21[0][2], cc21[1][2],cc21[2][2],cc21[3][2],cc21[4][2],cc21[5][2],cc21[6][2],cc21[7][2],cc21[8][2],cc21[9][2],
              cc21[10][2], cc21[11][2], cc21[12][2], cc21[13][2], cc21[14][2], cc21[15][2], cc21[16][2], cc21[17][2], 
              cc22[0][2], cc22[1][2],cc22[2][2],cc22[3][2],cc22[4][2],cc22[5][2],cc22[6][2],cc22[7][2],cc21[8][2],
              cc22[9][2], cc22[10][2], cc22[11][2], cc22[12][2], cc22[13][2]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s4=pd.Series([cc21[0][3], cc21[1][3],cc21[2][3],cc21[3][3],cc21[4][3],cc21[5][3],cc21[6][3],cc21[7][3],cc21[8][3],cc21[9][3],
              cc21[10][3], cc21[11][3], cc21[12][3], cc21[13][3], cc21[14][3], cc21[15][3], cc21[16][3], cc21[17][3], 
              cc22[0][3], cc22[1][3],cc22[2][3],cc22[3][3],cc22[4][3],cc22[5][3],cc22[6][3],cc22[7][3],cc21[8][3],
              cc22[9][3], cc22[10][3], cc22[11][3], cc22[12][3], cc22[13][3]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s5=pd.Series([cc21[0][4], cc21[1][4],cc21[2][4],cc21[3][4],cc21[4][4],cc21[5][4],cc21[6][4],cc21[7][4],cc21[8][4],cc21[9][4],
              cc21[10][4], cc21[11][4], cc21[12][4], cc21[13][4], cc21[14][4], cc21[15][4], cc21[16][4], cc21[17][4], 
              cc22[0][4], cc22[1][4],cc22[2][4],cc22[3][4],cc22[4][4],cc22[5][4],cc22[6][4],cc22[7][4],cc21[8][4],
              cc22[9][4], cc22[10][4], cc22[11][4], cc22[12][4], cc22[13][4]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s6=pd.Series([cc21[0][5], cc21[1][5],cc21[2][5],cc21[3][5],cc21[4][5],cc21[5][5],cc21[6][5],cc21[7][5],cc21[8][5],cc21[9][5],
              cc21[10][5], cc21[11][5], cc21[12][5], cc21[13][5], cc21[14][5], cc21[15][5], cc21[16][5], cc21[17][5], 
              cc22[0][5], cc22[1][5],cc22[2][5],cc22[3][5],cc22[4][5],cc22[5][5],cc22[6][5],cc22[7][5],cc21[8][5],
              cc22[9][5], cc22[10][5], cc22[11][5], cc22[12][5], cc22[13][5]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s7=pd.Series([cc21[0][6], cc21[1][6],cc21[2][6],cc21[3][6],cc21[4][6],cc21[5][6],cc21[6][6],cc21[7][6],cc21[8][6],cc21[9][6],
              cc21[10][6], cc21[11][6], cc21[12][6], cc21[13][6], cc21[14][6], cc21[15][6], cc21[16][6], cc21[17][6], 
              cc22[0][6], cc22[1][6],cc22[2][6],cc22[3][6],cc22[4][6],cc22[5][6],cc22[6][6],cc22[7][6],cc21[8][6],
              cc22[9][6], cc22[10][6], cc22[11][6], cc22[12][6], cc22[13][6]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
#unir en dataframe
CoefCorrel = pd.concat([s1, s2, s3, s4, s5, s6, s7], axis = 1)
CoefCorrel.columns = ['r_TD_Tr', 'p_TD_Tr', 'r_TD_Te', 'p_TD_Te', 'r_Tr_Te', 'p_Tr_Te', 'nº datos']
display(CoefCorrel)
CoefCorrel.describe()

,r_TD_Tr,p_TD_Tr,r_TD_Te,p_TD_Te,r_Tr_Te,p_Tr_Te,nº datos
Sem0 2021,0.031370,0.542630,-0.442141,1.432662e-19,-0.023955,0.642012,379
Sem1 2021,-0.000668,0.986203,-0.636375,1.425036e-77,0.005017,0.896709,672
Sem2 2021,-0.060015,0.120119,-0.502621,2.633099e-44,-0.001596,0.967053,672
Sem3 2021,-0.012018,0.755818,0.216960,1.334596e-08,0.059013,0.126443,672
Sem4 2021,0.022262,0.566002,-0.254183,2.701000e-11,0.050697,0.190976,667
Sem5 2021,0.031269,0.418365,0.086891,2.428848e-02,-0.026226,0.497331,672
Sem6 2021,0.049118,0.203486,0.444771,5.873126e-34,0.051356,0.183619,672
Sem7 2021,0.044132,0.253266,0.659492,4.198765e-85,0.050363,0.192247,672
Sem8 2021,0.082938,0.127500,0.620686,1.731705e-37,0.009223,0.865651,339
Sem9 2021,0.137079,0.523002,-0.247330,2.439391e-01,0.291262,0.167318,24
Sem10 2021,0.024251,0.531196,0.214326,2.163855e-08,0.000911,0.981229,669
Sem11 2021,0.060448,0.117466,0.242139,2.015333e-10,-0.022288,0.564099,672
Sem12 2021,0.081290,0.035132,0.729520,1.246242e-112,0.048197,0.212100,672
Sem13 2021,0.094717,0.014400,0.461109,2.019205e-36,0.049898,0.198067,667
Sem14 2021,0.090472,0.018989,0.697745,3.774192e-99,0.048358,0.210578,672
Sem15 2021,0.004169,0.914090,0.723062,9.729146e-110,0.021981,0.569477,672
Sem0162021,0.014689,0.703867,0.654268,2.415072e-83,-0.071423,0.064254,672
Sem17 2021,-0.002819,0.941858,0.620492,9.242834e-73,-0.003473,0.928405,672
Sem0 2022,0.024181,0.685970,0.435047,1.888234e-14,-0.000794,0.989412,282
Sem1 2022,0.015117,0.695680,0.672376,1.343508e-89,0.027156,0.482193,672
Sem2 2022,-0.018713,0.628226,0.528087,1.576706e-49,-0.034842,0.367165,672
Sem3 2022,-0.020825,0.589950,0.154779,5.597822e-05,0.049926,0.196139,672
Sem4 2022,0.025392,0.512053,0.567328,3.014956e-58,0.011204,0.772382,669
Sem5 2022,0.043899,0.257563,0.221200,7.752590e-09,-0.044241,0.253868,667
Sem6 2022,0.059266,0.352671,0.647298,7.703336e-31,-0.046426,0.466722,248
Sem7 2022,0.035541,0.427322,0.643857,5.382587e-60,0.013739,0.759016,501
Sem8 2021,0.082938,0.127500,0.620686,1.731705e-37,0.009223,0.865651,339
Sem9 2022,-0.007679,0.843088,0.417958,1.385326e-29,-0.082015,0.034197,667
Sem10 2022,0.046584,0.227817,0.652447,9.728351e-83,-0.019413,0.615413,672
Sem11 2022,0.045862,0.235110,0.247661,7.523964e-11,-0.090194,0.019360,672
Sem12 2022,0.056912,0.174063,0.759397,1.747465e-108,0.038079,0.363323,572
Sem13 2022,0.160539,0.000414,0.367232,9.018332e-17,-0.068645,0.133152,480

,r_TD_Tr,p_TD_Tr,r_TD_Te,p_TD_Te,r_Tr_Te,p_Tr_Te,nº datos
count,32.000000,32.000000,32.000000,3.200000e+01,32.000000,32.000000,32.000000
mean,0.038803,0.422838,0.350755,8.383863e-03,0.009377,0.461736,581.062500
std,0.045955,0.297042,0.389115,4.319758e-02,0.066774,0.321080,167.621105
min,-0.060015,0.000414,-0.636375,1.246242e-112,-0.090194,0.019360,24.000000
25%,0.012059,0.162422,0.216301,1.068780e-77,-0.024523,0.191930,554.250000
50%,0.033456,0.422843,0.452940,1.096188e-36,0.007120,0.416944,672.000000
75%,0.059561,0.642662,0.648585,3.906741e-11,0.048237,0.762358,672.000000
max,0.160539,0.986203,0.759397,2.439391e-01,0.291262,0.989412,672.000000

In [7]:
ordenar_valores_cc (CoefCorrel, 'r_TD_Tr', 'p_TD_Tr', 'r_TD_Te', 'p_TD_Te', 'r_Tr_Te', 'p_Tr_Te')

         r_TD_Tr  r_TD_Te  r_Tr_Te
cc>0.5         0       15        0
cc>0          25       12       18
cc>-0.5        7        3       14
cc>-1          0        2        0
total         32       32       32

# 1.2) ¿Las oscilaciones diarias vienen del ramal? Coef a partir de las temperaturas suavizadas

In [8]:
def cc_Tr_Tc_Te(DataframeCruce, DataframeExterior):#Función adaptada para variables suavizadas
    """
    Atributos:
    1) DataframeCruce: Lista de dataframes por semanas correspondiente a los datos de un mes de Cruce
    2) DataframeExterior: Lista de dataframes por semanas correspondiente a los datos de un mes de Exterior
    
    Devuelve:
    Una lista de listas, r. Cada elemento de r, r[i] con i=0, 1, 2, 3, 4, es una lista con los coeficiente de correlación y p 
    valores correspondientes a una semana.  r[i] = r_TD_Tr, p_TD_Tr, r_TD_Te, p_TD_Te, r_Tr_Te, p_Tr_Te
    
    ¿A qué corresponde cada elemento de r[i]?
    1) r_TD_Tr: Coeficiente de correlación entre la temperatura del Cruce y del Ramal
    2) p_TD_Tr: P-valor correspondiente a r_TD_Tr
    3) r_TD_Te: Coeficiente de correlación entre la temperatura del Cruce y la exterior
    4) p_TD_Te: P-valor correspondiente a r_TD_Te
    5) r_Tr_Te: Coeficiente de correlación entre la temperatura del Ramal y la exterior
    6) p_Tr_Te: P-valor correspondiente a r_Tr_Te
    """
    i=0
    r=[]
    while i<len(DataframeCruce):
       #print(i)
        DataframeCruce[i].reset_index(drop=True, inplace=True)
        DataframeExterior[i].reset_index(drop=True, inplace=True)
        
        # Variables que me van a hacer falta: Tc, Te, Tr
        for index, _ in DataframeExterior[i].iterrows():#Se va fuera de indice
            if  __builtins__.sum([pd.isna(DataframeCruce[i]['Tc_suavizada'][index]),
                                  pd.isna(DataframeCruce[i]['Tr_suavizada'][index]),
                                  pd.isna(DataframeExterior[i]['Te_suavizada'][index])]) > 0:
                DataframeCruce[i].drop([index], axis=0, inplace=True)
                DataframeExterior[i].drop([index], axis=0, inplace=True)

        #Mediante scipy por semanas:
        r_TD_Tr, p_TD_Tr = stats.pearsonr(DataframeCruce[i]['Tc_suavizada'], DataframeCruce[i]['Tr_suavizada'])
        r_TD_Te, p_TD_Te = stats.pearsonr(DataframeCruce[i]['Tc_suavizada'], DataframeExterior[i]['Te_suavizada'])
        r_Tr_Te, p_Tr_Te = stats.pearsonr(DataframeCruce[i]['Tr_suavizada'], DataframeExterior[i]['Te_suavizada'])
        rs = r_TD_Tr, p_TD_Tr, r_TD_Te, p_TD_Te, r_Tr_Te, p_Tr_Te, len(DataframeCruce[i]['Tr_suavizada'])
        r.append(rs)
        i=i+1
    return(r)

In [9]:
cc21 = cc_Tr_Tc_Te(SemanaCruce21, SemanaExterior21)
cc22 = cc_Tr_Tc_Te(SemanaCruce22, SemanaExterior22)

In [10]:
s1=pd.Series([cc21[0][0], cc21[1][0],cc21[2][0],cc21[3][0],cc21[4][0],cc21[5][0],cc21[6][0],cc21[7][0],cc21[8][0],cc21[9][0],
              cc21[10][0], cc21[11][0], cc21[12][0], cc21[13][0], cc21[14][0], cc21[15][0], cc21[16][0], cc21[17][0], 
              cc22[0][0], cc22[1][0],cc22[2][0],cc22[3][0],cc22[4][0],cc22[5][0],cc22[6][0],cc22[7][0],cc21[8][0],
              cc22[9][0], cc22[10][0], cc22[11][0], cc22[12][0], cc22[13][0]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s2=pd.Series([cc21[0][1], cc21[1][1],cc21[2][1],cc21[3][1],cc21[4][1],cc21[5][1],cc21[6][1],cc21[7][1],cc21[8][1],cc21[9][1],
              cc21[10][1], cc21[11][1], cc21[12][1], cc21[13][1], cc21[14][1], cc21[15][1], cc21[16][1], cc21[17][1], 
              cc22[0][1], cc22[1][1],cc22[2][1],cc22[3][1],cc22[4][1],cc22[5][1],cc22[6][1],cc22[7][1],cc21[8][1],
              cc22[9][1], cc22[10][1], cc22[11][1], cc22[12][1], cc22[13][1]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s3=pd.Series([cc21[0][2], cc21[1][2],cc21[2][2],cc21[3][2],cc21[4][2],cc21[5][2],cc21[6][2],cc21[7][2],cc21[8][2],cc21[9][2],
              cc21[10][2], cc21[11][2], cc21[12][2], cc21[13][2], cc21[14][2], cc21[15][2], cc21[16][2], cc21[17][2], 
              cc22[0][2], cc22[1][2],cc22[2][2],cc22[3][2],cc22[4][2],cc22[5][2],cc22[6][2],cc22[7][2],cc21[8][2],
              cc22[9][2], cc22[10][2], cc22[11][2], cc22[12][2], cc22[13][2]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s4=pd.Series([cc21[0][3], cc21[1][3],cc21[2][3],cc21[3][3],cc21[4][3],cc21[5][3],cc21[6][3],cc21[7][3],cc21[8][3],cc21[9][3],
              cc21[10][3], cc21[11][3], cc21[12][3], cc21[13][3], cc21[14][3], cc21[15][3], cc21[16][3], cc21[17][3], 
              cc22[0][3], cc22[1][3],cc22[2][3],cc22[3][3],cc22[4][3],cc22[5][3],cc22[6][3],cc22[7][3],cc21[8][3],
              cc22[9][3], cc22[10][3], cc22[11][3], cc22[12][3], cc22[13][3]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s5=pd.Series([cc21[0][4], cc21[1][4],cc21[2][4],cc21[3][4],cc21[4][4],cc21[5][4],cc21[6][4],cc21[7][4],cc21[8][4],cc21[9][4],
              cc21[10][4], cc21[11][4], cc21[12][4], cc21[13][4], cc21[14][4], cc21[15][4], cc21[16][4], cc21[17][4], 
              cc22[0][4], cc22[1][4],cc22[2][4],cc22[3][4],cc22[4][4],cc22[5][4],cc22[6][4],cc22[7][4],cc21[8][4],
              cc22[9][4], cc22[10][4], cc22[11][4], cc22[12][4], cc22[13][4]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s6=pd.Series([cc21[0][5], cc21[1][5],cc21[2][5],cc21[3][5],cc21[4][5],cc21[5][5],cc21[6][5],cc21[7][5],cc21[8][5],cc21[9][5],
              cc21[10][5], cc21[11][5], cc21[12][5], cc21[13][5], cc21[14][5], cc21[15][5], cc21[16][5], cc21[17][5], 
              cc22[0][5], cc22[1][5],cc22[2][5],cc22[3][5],cc22[4][5],cc22[5][5],cc22[6][5],cc22[7][5],cc21[8][5],
              cc22[9][5], cc22[10][5], cc22[11][5], cc22[12][5], cc22[13][5]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
s7=pd.Series([cc21[0][6], cc21[1][6],cc21[2][6],cc21[3][6],cc21[4][6],cc21[5][6],cc21[6][6],cc21[7][6],cc21[8][6],cc21[9][6],
              cc21[10][6], cc21[11][6], cc21[12][6], cc21[13][6], cc21[14][6], cc21[15][6], cc21[16][6], cc21[17][6], 
              cc22[0][6], cc22[1][6],cc22[2][6],cc22[3][6],cc22[4][6],cc22[5][6],cc22[6][6],cc22[7][6],cc21[8][6],
              cc22[9][6], cc22[10][6], cc22[11][6], cc22[12][6], cc22[13][6]],
            index = ['Sem0 2021','Sem1 2021','Sem2 2021','Sem3 2021','Sem4 2021','Sem5 2021','Sem6 2021','Sem7 2021','Sem8 2021',
                    'Sem9 2021','Sem10 2021','Sem11 2021','Sem12 2021','Sem13 2021','Sem14 2021','Sem15 2021','Sem0162021',
                     'Sem17 2021','Sem0 2022','Sem1 2022','Sem2 2022','Sem3 2022','Sem4 2022','Sem5 2022','Sem6 2022','Sem7 2022','Sem8 2021',
                    'Sem9 2022','Sem10 2022','Sem11 2022','Sem12 2022','Sem13 2022'])
#unir en dataframe
CoefCorrel = pd.concat([s1, s2, s3, s4, s5, s6, s7], axis = 1)
CoefCorrel.columns = ['r_TD_Tr', 'p_TD_Tr', 'r_TD_Te', 'p_TD_Te', 'r_Tr_Te', 'p_Tr_Te', 'nº datos']
display(CoefCorrel)
CoefCorrel.describe()

,r_TD_Tr,p_TD_Tr,r_TD_Te,p_TD_Te,r_Tr_Te,p_Tr_Te,nº datos
Sem0 2021,-0.000601,9.906942e-01,-0.546704,6.372187e-31,-0.029920,5.614492e-01,379
Sem1 2021,-0.016933,6.612574e-01,-0.709943,4.145792e-104,0.014672,7.041944e-01,672
Sem2 2021,-0.073068,5.833773e-02,-0.570587,2.661395e-59,-0.000420,9.913339e-01,672
Sem3 2021,-0.014819,7.013775e-01,0.265943,2.421144e-12,0.131249,6.477684e-04,672
Sem4 2021,0.011728,7.623895e-01,-0.309668,2.731457e-16,0.120338,1.849516e-03,667
Sem5 2021,0.107098,5.450584e-03,0.104935,6.475287e-03,-0.057430,1.369612e-01,672
Sem6 2021,0.142998,1.998867e-04,0.485979,4.008029e-41,0.125145,1.150468e-03,672
Sem7 2021,0.115220,2.778454e-03,0.695604,2.637864e-98,0.124358,1.236705e-03,672
Sem8 2021,0.165187,2.279587e-03,0.708978,4.715003e-53,0.010678,8.447043e-01,339
Sem9 2021,-0.302567,2.079987e-01,-0.759211,1.635084e-04,0.695988,9.344546e-04,19
Sem10 2021,0.062084,1.099691e-01,0.232900,1.249092e-09,-0.012574,7.463819e-01,664
Sem11 2021,0.142852,2.029359e-04,0.250336,4.627086e-11,-0.061139,1.133236e-01,672
Sem12 2021,0.211238,3.234765e-08,0.776260,2.224198e-136,0.092870,1.603196e-02,672
Sem13 2021,0.164292,2.006909e-05,0.508212,4.339586e-45,0.096280,1.285778e-02,667
Sem14 2021,0.202431,1.205015e-07,0.739658,2.409622e-117,0.106322,5.800115e-03,672
Sem15 2021,0.058110,1.323617e-01,0.761943,1.591006e-128,0.047716,2.167023e-01,672
Sem0162021,0.022243,5.648885e-01,0.707577,3.978691e-103,-0.143699,1.857961e-04,672
Sem17 2021,0.063947,9.765857e-02,0.676447,4.572303e-91,-0.007167,8.528821e-01,672
Sem0 2022,0.073087,2.211307e-01,0.559933,1.132327e-24,-0.033143,5.794074e-01,282
Sem1 2022,0.061445,1.115246e-01,0.701854,8.602091e-101,0.073582,5.658624e-02,672
Sem2 2022,-0.030605,4.283094e-01,0.544688,3.517632e-53,-0.055574,1.501306e-01,672
Sem3 2022,-0.058458,1.300568e-01,0.151116,8.399865e-05,0.113868,3.117295e-03,672
Sem4 2022,0.048416,2.110511e-01,0.603870,1.024191e-67,0.024965,5.191811e-01,669
Sem5 2022,0.096355,1.278807e-02,0.235299,7.646622e-10,-0.108387,5.074954e-03,667
Sem6 2022,0.061823,3.322461e-01,0.665671,4.069218e-33,-0.112836,7.612494e-02,248
Sem7 2022,0.041091,3.611236e-01,0.679058,2.515515e-68,0.014240,7.517320e-01,496
Sem8 2021,0.165187,2.279587e-03,0.708978,4.715003e-53,0.010678,8.447043e-01,339
Sem9 2022,0.007185,8.530603e-01,0.435450,3.078184e-32,-0.190782,6.918638e-07,667
Sem10 2022,0.101769,8.288022e-03,0.677191,2.450014e-91,-0.034050,3.781648e-01,672
Sem11 2022,0.064987,9.231670e-02,0.257892,1.136778e-11,-0.179977,2.662874e-06,672
Sem12 2022,0.126098,2.516893e-03,0.784291,2.812266e-120,0.082183,4.946683e-02,572
Sem13 2022,0.358611,5.167104e-16,0.392037,4.395553e-19,-0.121823,7.539766e-03,480

,r_TD_Tr,p_TD_Tr,r_TD_Te,p_TD_Te,r_Tr_Te,p_Tr_Te,nº datos
count,32.000000,3.200000e+01,32.000000,3.200000e+01,32.000000,3.200000e+01,32.000000
mean,0.068076,2.207674e-01,0.356750,2.100874e-04,0.023007,2.696832e-01,580.593750
std,0.111233,2.907586e-01,0.459041,1.143717e-03,0.153499,3.409922e-01,168.155239
min,-0.302567,5.167104e-16,-0.759211,2.224198e-136,-0.190782,6.918638e-07,19.000000
25%,0.010593,2.457566e-03,0.234699,1.837510e-91,-0.056038,2.800350e-03,553.000000
50%,0.063016,1.038138e-01,0.526450,2.169793e-45,0.010678,6.635559e-02,672.000000
75%,0.130287,3.394655e-01,0.697167,6.054908e-13,0.093722,5.659388e-01,672.000000
max,0.358611,9.906942e-01,0.784291,6.475287e-03,0.695988,9.913339e-01,672.000000

In [11]:
ordenar_valores_cc (CoefCorrel, 'r_TD_Tr', 'p_TD_Tr', 'r_TD_Te', 'p_TD_Te', 'r_Tr_Te', 'p_Tr_Te')

         r_TD_Tr  r_TD_Te  r_Tr_Te
cc>0.5         0       17        1
cc>0          25       10       16
cc>-0.5        7        1       15
cc>-1          0        4        0
total         32       32       32